services:
  Redis:
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'

  octave.tools.redis.helper:
    class: Octave\ToolsBundle\Util\RedisHelper
    public: true
    arguments:
      - '@Redis'
      - '%octave.tools.cache_prefix%'
      - '@router'

  octave.tools.clear.cache.command:
    class: Octave\ToolsBundle\Command\ClearRedisCacheCommand
    arguments:
      - '@octave.tools.redis.helper'
    tags:
      - { name: console.command }
    public: true

  octave.tools.warm-up.cache.command:
    class: Octave\ToolsBundle\Command\WarmUpRedisCacheCommand
    arguments:
      - '@octave.tools.redis.helper'
      - '@http_client'
      - '%octave.tools.auth_username%'
      - '%octave.tools.auth_password%'
    tags:
      - { name: console.command }
    public: true

  octave.tools.info.command:
    class: Octave\ToolsBundle\Command\InfoRedisCacheCommand
    arguments:
      - '@octave.tools.redis.helper'
    tags:
      - { name: console.command }
    public: true

  Octave\ToolsBundle\Util\RedisHelper:
    alias: 'octave.tools.redis.helper'

  octave.cache.listener:
    class: Octave\ToolsBundle\EventListener\CacheListener
    arguments:
      - '@octave.tools.redis.helper'
      - '@router'
      - '@mobile_detect.mobile_detector.default'
      - '%locale%'
      - '%kernel.environment%'
      - '%octave.tools.cache_prefix%'
    tags:
      - {name: kernel.event_subscriber}
