services:

    octave.tools.form.serializer:
        class: Octave\ToolsBundle\Service\FormSerializer
        public: true

    Octave\ToolsBundle\Service\FormSerializer:
        alias: octave.tools.form.serializer
        public: true

    octave.tools.recaptcha.checker:
        class: Octave\ToolsBundle\Util\RecaptchaChecker
        public: true
        arguments:
            - '%octave.tools.recaptcha_secret%'

    Octave\ToolsBundle\Util\RecaptchaChecker:
        alias: octave.tools.recaptcha.checker
        public: true

    octave.tools.assets.version.command:
        class: Octave\ToolsBundle\Command\ChangeAssetVersionCommand
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: console.command}
        public: true