services:

    octave.tools.form.serializer:
        class: Octave\ToolsBundle\Service\FormSerializer
        public: true

    Octave\ToolsBundle\Service\FormSerializer:
        alias: octave.tools.form.serializer
        public: true

    octave.tools.recaptcha.checker:
        class: Octave\ToolsBundle\Util\RecaptchaChecker
        public: true
        arguments:
            - '%octave.tools.recaptcha_secret%'

    Octave\ToolsBundle\Util\RecaptchaChecker:
        alias: octave.tools.recaptcha.checker
        public: true

    octave.tools.assets.version.command:
        class: Octave\ToolsBundle\Command\ChangeAssetVersionCommand
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: console.command}
        public: true

    octave.tools.clear.cache:
        class: Octave\ToolsBundle\Command\ClearRedisCacheCommand
        arguments:
            - '@octave.redis.helper'
        tags:
            - { name: console.command }
        public: true

    Redis:
        class: Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'

    octave.redis.helper:
        class: Octave\ToolsBundle\Util\RedisHelper
        public: true
        arguments:
            - '@Redis'
            - '%octave.tools.cache_prefix%'

    Octave\ToolsBundle\Util\RedisHelper:
        alias: 'octave.redis.helper'

    octave.cache.listener:
        class: Octave\ToolsBundle\EventListener\CacheListener
        arguments:
            - '@octave.redis.helper'
            - '@router'
            - '%locale%'
            - '%kernel.environment%'
            - '%octave.tools.cache_prefix%'
        tags:
            - { name: kernel.event_subscriber }

