services:

    octave.tools.form.serializer:
        class: Octave\ToolsBundle\Service\FormSerializer

    octave.tools.recaptcha.checker:
        class: Octave\ToolsBundle\Util\RecaptchaChecker
        arguments:
            - '%octave.tools.recaptcha_secret%'

    octave.tools.assets.version.command:
        class: Octave\Command\ChangeAssetVersionCommand
        tags:
            - { name: console.command}